### PR TITLE
Fixing pandastrike/huxley#11: Don't update if records are the same

### LINKED ISSUE #11: Upgrade Kick Server to Recognize Already-Set DNS Records
If the sidekick server is asked to set a DNS record, it should check to see if that record already exists as specified.  This would save time during iterations.  This would require a change to the pandastrike/panda-hook repository.

### PR DESCRIPTION
**Pull request by PandaWhisperer**
This fixes https://github.com/pandastrike/huxley/issues/11

### CODE REVIEW

File: src/route53.coffee [hunk 1]
```diff
@@ -114,7 +114,13 @@ module.exports = (config) ->
     # We need to determine if the requested hostname is currently assigned in a DNS record.
     {current_ip_address, current_type} = yield @get_current_record(record.hostname, record.zone_id)
 
-    if current_ip_address?
+    if current_ip_address == record.ip_address and
```
Comment (freeformflow) [inline src/route53.coffee:117]: This is very minor point, but Dan has mentioned that he and Matthew prefer to see `&&` and  `||` instead of `and` and `or`.  It's not a super big deal, but as you code on stuff directly reviewed by Dan (particularly fairmont) he may mention it to you.
